Tests and objects added
objectionary/flatty pull request #33
Opened 2023-06-01 18:11 UTC by EugeneDar

Closes: #32

2023-06-01 18:17 UTC, EugeneDar commented
@Graur please, have a look

2023-06-02 08:32 UTC, Graur requested changes

2023-06-02 10:16 UTC, EugeneDar commented on src/main/java/org/objectionary/entities/ObjectWithApplication.java
> +public final class ObjectWithApplication extends Entity {
@Graur fixed, please have a look again

2023-06-02 12:03 UTC, Graur commented on src/main/java/org/objectionary/entities/ObjectWithApplication.java
> +public final class ObjectWithApplication extends Entity {
@EugeneDar Great! You can mark this suggesting as `resolved`

2023-06-02 12:04 UTC, Graur approved these changes
@EugeneDar Good one
@yegor256 Please, have a look

2023-06-02 12:18 UTC, EugeneDar commented
@yegor256 please, have a look

2023-06-02 12:44 UTC, yegor256 commented
@rultor merge

2023-06-02 12:46 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/32401-1573677214)

2023-06-02 12:47 UTC, merged

2023-06-02 12:48 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/32401-1573677214) (took me 2min)