Parser tests added
objectionary/flatty pull request #36
Opened 2023-06-13 13:23 UTC by EugeneDar

Closes: #23

---

## PR-Codex overview
This PR adds a new `Parser` class to the codebase and its corresponding test class. The `Parser` class is responsible for parsing a given input and returning a parsed `ObjectsBox`. 

### Detailed summary
- Added `Parser` class to the codebase.
- Added `ParserTest` class to test the `Parser` class.
- The `Parser` class has a constructor that takes an input string.
- The `Parser` class has a `parse()` method that returns a parsed `ObjectsBox`.
- The `ParserTest` class has test methods to test the `Parser` class.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2023-06-13 13:29 UTC, EugeneDar commented
@Graur please, have a look. And before it check please my comments below.

Tests would be redundant if they completely covered every case of different object structure, since the tests from `ObjectsBoxTest` already do that. For this reason, it seems to me that these tests are sufficient.

You may also notice that in the two tests I check a boolean variable for truth instead of comparing strings. This is due to the fact that this testing framefork makes incorrect comparisons if there is a line break in the strings. For this reason, I suggest leaving it as it is now, unless you have other ideas on how to solve this problem other than just comparing strings via `equals`.

2023-06-13 14:05 UTC, Graur requested changes

2023-06-13 18:48 UTC, EugeneDar commented on src/test/java/org/objectionary/ParserTest.java
> +            Matchers.equalTo(true)
@Graur thank you, fixed it?

2023-06-13 18:48 UTC, EugeneDar commented
@Graur please, have a look again.

2023-06-13 20:55 UTC, Graur approved these changes
@EugeneDar Good one!
@yegor256 Please, have a look

2023-06-14 14:39 UTC, EugeneDar commented
@yegor256 please, have a look

2023-06-14 14:44 UTC, yegor256 commented
@rultor merge

2023-06-14 14:46 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/32626-1591368921)

2023-06-14 14:47 UTC, merged

2023-06-14 14:48 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/32626-1591368921) (took me 2min)